# Generated by Django 3.0.11 on 2021-02-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210207_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfilecontent',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pic',
        ),
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ManyToManyField(related_name='contents', to='accounts.PostFileContent'),
        ),
    ]
