# Generated by Django 3.0.11 on 2021-02-07 11:26

import accounts.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210207_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfilecontent',
            name='post',
            field=models.ForeignKey(default='15', on_delete=django.db.models.deletion.CASCADE, related_name='post_image', to='accounts.Post'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='post',
            name='pic',
        ),
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(default='15', upload_to=accounts.models.post_image_directory_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
            preserve_default=False,
        ),
    ]
