# Generated by Django 3.0.11 on 2021-01-24 13:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertise_with_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_Name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('Business_Website', models.URLField(blank=True, null=True)),
                ('Business_Facebook', models.URLField(blank=True, null=True)),
                ('Business_Instagram', models.URLField(blank=True, null=True)),
                ('Business_Twitter', models.URLField(blank=True, null=True)),
                ('Business_Linkedin', models.URLField(blank=True, null=True)),
                ('Business_Pinterest', models.URLField(blank=True, null=True)),
                ('Business_Github', models.URLField(blank=True, null=True)),
                ('Business_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Business_Location', mapbox_location_field.models.LocationField(map_attrs={})),
                ('Business_Address', mapbox_location_field.models.AddressAutoHiddenField(blank=True, map_id='map', null=True)),
                ('Business_Telephone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('0?[5-9]{1}\\d{9}$')])),
                ('Business_WhatsApp', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('0?[5-9]{1}\\d{9}$')])),
                ('Business_Description', models.TextField()),
                ('Business_Logo', models.ImageField(upload_to='advertise/logo', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('Business_Images', models.ImageField(blank=True, null=True, upload_to='advertise/images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Business Images')),
                ('Business_Established_Date', models.DateField()),
                ('Added_at', models.DateTimeField(auto_now_add=True)),
                ('view', models.PositiveIntegerField(default=0)),
                ('Added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertise With Us',
                'verbose_name_plural': 'Advertise With Us',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/icons', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('description', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='categories/cover')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('0?[5-9]{1}\\d{9}$')])),
                ('msg', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('0?[5-9]{1}\\d{9}$')])),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Free_Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_Name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('Business_Website', models.URLField(blank=True, null=True)),
                ('Business_Facebook', models.URLField(blank=True, null=True)),
                ('Business_Instagram', models.URLField(blank=True, null=True)),
                ('Business_Twitter', models.URLField(blank=True, null=True)),
                ('Business_Linkedin', models.URLField(blank=True, null=True)),
                ('Business_Pinterest', models.URLField(blank=True, null=True)),
                ('Business_Github', models.URLField(blank=True, null=True)),
                ('Business_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Business_Location', mapbox_location_field.models.LocationField(map_attrs={})),
                ('Business_Address', mapbox_location_field.models.AddressAutoHiddenField(blank=True, map_id='map', null=True)),
                ('Business_Telephone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('0?[5-9]{1}\\d{9}$')])),
                ('Business_WhatsApp', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('0?[5-9]{1}\\d{9}$')])),
                ('Business_Description', models.TextField()),
                ('Business_Logo', models.ImageField(upload_to='listing/logo', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('Business_Images', models.ImageField(blank=True, null=True, upload_to='listing/images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Business Images')),
                ('Business_Established_Date', models.DateField()),
                ('Listed_at', models.DateTimeField(auto_now_add=True)),
                ('view', models.PositiveIntegerField(default=0)),
                ('Business_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.Category')),
            ],
            options={
                'verbose_name': 'Free Listing',
                'verbose_name_plural': 'Free Listings',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.Free_Listing')),
            ],
        ),
        migrations.CreateModel(
            name='SaleBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.Customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('0?[5-9]{1}\\d{9}$')])),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('gstin', models.CharField(max_length=15, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.Free_Listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='subcategories/icons', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('image', models.ImageField(blank=True, null=True, upload_to='subcategories/images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('description', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='subcategories/cover')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.Category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stocks/images')),
                ('hsn', models.CharField(max_length=200, verbose_name='HSN Number')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.Free_Listing')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.Supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Skill')),
                ('excellence', models.IntegerField(default=0, help_text='Value between 0 & 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('color', models.CharField(default='#A01038', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgst', models.FloatField(blank=True, null=True, verbose_name='CGST (in %)')),
                ('sgst', models.FloatField(blank=True, null=True, verbose_name='SGST (in %)')),
                ('igst', models.FloatField(blank=True, null=True, verbose_name='IGST (in %)')),
                ('quantity', models.IntegerField(default=1)),
                ('perPrice', models.IntegerField(default=1)),
                ('totalPrice', models.IntegerField(default=1)),
                ('billNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.SaleBill')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.Stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgst', models.FloatField(blank=True, null=True, verbose_name='CGST (in %)')),
                ('sgst', models.FloatField(blank=True, null=True, verbose_name='SGST (in %)')),
                ('igst', models.FloatField(blank=True, null=True, verbose_name='IGST (in %)')),
                ('quantity', models.IntegerField(default=1)),
                ('perPrice', models.IntegerField(default=1)),
                ('totalPrice', models.IntegerField(default=1)),
                ('billNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.PurchaseBill')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.Stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.Supplier'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product/images')),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
                ('offer_price', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.Free_Listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreeListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing/images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.Free_Listing')),
            ],
        ),
        migrations.AddField(
            model_name='free_listing',
            name='Business_Subcategory',
            field=models.ManyToManyField(max_length=5, to='pazar.Subcategory'),
        ),
        migrations.AddField(
            model_name='free_listing',
            name='Listed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='free_listing',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Tag your business here', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Business Keywords'),
        ),
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.Free_Listing'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('rate', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.Free_Listing')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertiseWithUsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertise/images', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('advertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.Advertise_with_Us')),
            ],
        ),
        migrations.AddField(
            model_name='advertise_with_us',
            name='Business_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pazar.Category'),
        ),
        migrations.AddField(
            model_name='advertise_with_us',
            name='Business_Subcategory',
            field=models.ManyToManyField(to='pazar.Subcategory'),
        ),
        migrations.AddField(
            model_name='advertise_with_us',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Tag your business here', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Business Keywords'),
        ),
    ]
