# Generated by Django 3.0.11 on 2021-01-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pazar', '0003_auto_20210127_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=models.CharField(default='#CF2A31', max_length=7),
        ),
    ]
