# Generated by Django 3.0.11 on 2021-02-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pazar', '0006_auto_20210204_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=models.CharField(default='#D79DF9', max_length=7),
        ),
    ]
