# Generated by Django 3.0.11 on 2021-02-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pazar', '0007_auto_20210204_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=models.CharField(default='#A41D6D', max_length=7),
        ),
    ]
