# Generated by Django 3.0.11 on 2021-02-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pazar', '0012_auto_20210206_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=models.CharField(default='#D2F7BB', max_length=7),
        ),
    ]
