# Generated by Django 3.0.11 on 2021-02-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pazar', '0013_auto_20210206_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=models.CharField(default='#91A6B2', max_length=7),
        ),
    ]
