# Generated by Django 3.0.11 on 2021-02-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pazar', '0014_auto_20210207_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=models.CharField(default='#27BD56', max_length=7),
        ),
    ]
